version: 0.2

phases: 
  install: 
    commands: 
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
      - "unzip terraform_1.0.5_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - pwd
      - ls
      - cd terra 
      - ls
      - terraform init -upgrade
      - terraform workspace new $WORKSPACE
      - terraform workspace select $WORKSPACE


      

  build:
    commands:
      - terraform $TF_COMMAND -var-file="../environment/intput_var.auto.tfvars" $AUTO

  post_build:
    commands:
      - echo "terraform $TF_COMMAND completed on ´date´"